# Birds CUB dataset
birds_images_path: '/w/247/zyanliu/data/CUB_200_2011/images/'
birds_embedding_path: '/w/247/zyanliu/data/cub_icml/'
birds_text_path: '/w/247/zyanliu/data/captioned_cub_2016cvpr/text_c10/'
birds_dataset_path: '/w/247/zyanliu/csc2516_project/Text-to-Image-Synthesis/birds_bert.hdf5'
val_split_path: '/w/247/zyanliu/data/cub_icml/valclasses.txt'
train_split_path: '/w/247/zyanliu/data/cub_icml/trainclasses.txt'
test_split_path: '/w/247/zyanliu/data/cub_icml/testclasses.txt'


# # flowers dataset
# flowers_images_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/'
# flowers_embedding_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/'
# flowers_text_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/cvpr2016_flowers/text_c10/'
# flowers_dataset_path: '/scratch/aelnouby/text2image/flowers.hdf5'

# flowers_val_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/valclasses.txt'
# flowers_train_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/trainclasses.txt'
# flowers_test_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/testclasses.txt'